# Pandas -> Data Analysis Library
## Built on top of Numpy

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Salary_Data.csv")
# Data Frame Like Dictionary ok Keys and Values -> Where Key represent Column and Values represent Values of This Columns

In [3]:
df.head() # Return First 5 Rows From DF

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.tail() # Return Last 5 Rows From DF

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
df.info() # Return Info Like # of Rows, # of Columns, # of Non-Missng Values in Each Column, Data Type of Each Column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes

In [6]:
df.describe() # return Statistical Info for Numerical Columns

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [7]:
df.shape # Attribute that Return a Tuple of #ofRows and #ofColumns (Rows, Columns)

(30, 2)

In [8]:
pd.set_option('display.max_columns', 2)
pd.set_option('display.max_rows', 10)

# configure global settings that affect the behavior of Pandas operations and outputs. It allows you to customize how data is displayed, manipulated, or handled in your DataFrame.

In [9]:
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
..              ...       ...
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

[30 rows x 2 columns]

# Create Data Frame

In [10]:
students = {"Std_ID":[100, 200, 300],
            "Name": ["Ahmed", "Ibrahim", "Mostafa"],
            "Mark": [20, 19, 18]}

In [11]:
df = pd.DataFrame(students)

In [12]:
df

   Std_ID  ... Mark
0     100  ...   20
1     200  ...   19
2     300  ...   18

[3 rows x 3 columns]

In [13]:
df['Age'] = [21, 24, 26]

In [14]:
df

   Std_ID  ... Age
0     100  ...  21
1     200  ...  24
2     300  ...  26

[3 rows x 4 columns]

In [16]:
# Series Like 1 column 
std_names = ["Ahmed", "Akram", "Amer"]
marks = [100, 200, 300]
x = pd.Series(data = marks, index= std_names)
x

Ahmed    100
Akram    200
Amer     300
dtype: int64